apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dmn1
  namespace: ns1
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: container1
        image: nginx:alpine
        ports:
        - containerPort: 80