apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
  namespace: ns1
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:   # template section is specification to create pods
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: container1
        image: nginx:alpine
        ports:
        - containerPort: 80