# Run as: C:/Users/sanee/vscode/.venv/Scripts/python.exe .\linear_regression.py

import pandas as pd

house_data = pd.read_csv("House_Price.csv", header=0, sep=",")

print(house_data)
print(house_data.head())
print(house_data.describe())
print(house_data.info())
print(house_data.columns)
print(house_data.shape)
print(house_data.dtypes)
print(house_data.isnull().sum())
print(house_data.corr())
print(house_data['Price'].mean())
print(house_data[['Size', 'Bedrooms']].head())
print(house_data[house_data['Price'] > 500000]) 
print(house_data.groupby('Bedrooms')['Price'].mean())
print(house_data.sort_values(by='Size', ascending=False).head())
print(house_data['Price'].value_counts())
print(house_data['Size'].min())
print(house_data['Size'].max())
print(house_data['Bedrooms'].unique())
print(house_data['Price'].median())
print(house_data['Price'].std())
print(house_data[['Size', 'Price']].corr())
print(house_data[['Bedrooms', 'Price']].corr())
print(house_data.sample(5))
print(house_data.dropna().shape)
print(house_data.fillna(house_data.mean()).shape)
print(house_data.rename(columns={'Size': 'SquareFeet'}).head())
print(house_data.duplicated().sum())
print(house_data.drop_duplicates().shape)
print(house_data['Price'].plot(kind='hist', bins=10, title='House Price Distribution'))
print(house_data[['Size', 'Price']].plot(kind='scatter', x='Size', y='Price', title='Size vs Price'))
print("House data analysis completed.")