import numpy as np
import pandas as pd

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(data, columns=['A', 'B', 'C'])    
# Display various properties and statistics of the numpy array and pandas DataFrame
print("Numpy Array:")
print(data) 
print("Array shape:", data.shape)
print("Array data type:", data.dtype)
print("Array mean:", np.mean(data))
print("Array sum:", np.sum(data))
print("Array standard deviation:", np.std(data))
print("Array transpose:")
print(data.T)
print("Array sliced (first two rows):")
print(data[:2, :])
print("Array sliced (first two columns):")
print(data[:, :2])
print("Array flattened:")
print(data.flatten())   
print("Dimensions of the array:", data.ndim)
print("Size of the array:", data.size)
print("Maximum value in the array:", np.max(data))
print("Minimum value in the array:", np.min(data))
print("Unique values in the array:", np.unique(data))
print("Sorted array:", np.sort(data, axis=None))    
print("Cumulative sum of the array:", np.cumsum(data))
print("Reshaped array (3x2):")
#print(data.reshape(3, 2))   
print("Array with 10 linearly spaced values between 0 and 1:")
print(np.linspace(0, 1, 10))
print("Random array of shape (2,3):")
print(np.random.rand(2, 3))
print("Random integers between 0 and 10 of shape (2,3):")
print(np.random.randint(0, 10, (2, 3)))
print("Array with NaN values:")
nan_array = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
print(nan_array)
print("\n")

print("DataFrame:")
print(df)
print("DataFrame shape:", df.shape)
print("DataFrame info:")
print(df.info())
print("Statistical summary:")
print(df.describe())
print("First two rows:")
print(df.head(2))
print("Last two rows:")
print(df.tail(2))
print("Column 'B' values:")
print(df['B'])
print("Rows where column 'A' > 4:")
print(df[df['A'] > 4])
print("Mean of each column:")
print(df.mean())
print("Sum of each column:")
print(df.sum())
print("Standard deviation of each column:")
print(df.std())
print("Correlation matrix:")
print(df.corr())
print("Sorted by column 'C':")
print(df.sort_values(by='C'))

